services:
  - type: web
    name: ocr-scanner
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: USE_CLOUDINARY
        value: "true"
      - key: TESSERACT_PATH
        value: "/usr/bin/tesseract"
      - key: PYTHON_VERSION
        value: "3.10"
